live_config_reload = true

[env]
TERM = "alacritty"

[window]
option_as_alt = "Both"
decorations_theme_variant = "Dark"
opacity = 0.90

[colors.primary]
foreground = "#F8F8F2"
background = "#272822"

[colors.normal]
black   = "#272822"
red     = "#F92672"
green   = "#A6E22E"
yellow  = "#F4BF75"
blue    = "#66D9EF"
magenta = "#AE81FF"
cyan    = "#A1EFE4"
white   = "#F8F8F2"

[colors.bright]
black   = "#75715E"
red     = "#F92672"
green   = "#A6E22E"
yellow  = "#F4BF75"
blue    = "#66D9EF"
magenta = "#AE81FF"
cyan    = "#A1EFE4"
white   = "#F9F8F5"

[colors.cursor]
text   = "#272822"
cursor = "#F8F8F2"

[colors.search.matches]
foreground = "#272822"
background = "#66D9EF"

[colors.search.focused_match]
foreground = "#272822"
background = "#AE81FF"

[colors.line_indicator]
foreground = "#F8F8F2"
background = "#005F87"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold]
style = "Bold"

[font.italic]
style = "Regular Italic"

[font.offset]
x = 1
y = 1
